import React from 'react';
import Head from 'next/head'
import Container from '../../components/Layout/Container';
import CardProject from '../../components/CardProject';

const Proyectos = () => {
    return (
        <>
            <Container>
                <Head>
                    <title>Hugo Mendoza - Portafolio</title>
                    <meta name="description" content="Generated by create next app" />
                </Head>
                <div className="index w-full text-gray-100">
                    <div className=" h-64 m-0 w-full flex flex-wrap content-center text-center p-5">
                        <div className="max-w-xl md:mx-auto sm:text-center lg:max-w-2xl">
                            <h2 className=" -max-w-lg mb-2 font-sans text-3xl font-bold leading-none tracking-tight sm:text-4xl md:mx-auto">
                                Conoce mis Proyectos
                            </h2>
                            <div className="mx-auto w-1/5 pt-3 border-b-2 border-primary mb-6" />
                            <p className="text-base md:text-lg">
                                Aqui puedes conocer algunos de los proyectos que he desarrollado en diferentes tecnologias
                            </p>
                        </div>
                    </div>
                </div>

                <div className="bg-gray-200 w-full">
                    <div className="container grid grid-cols- md:grid-cols-2 lg:grid-cols-3  w-full">

                        {/* {posts.map((post, index) => (
    <CardPost key={index}
        post={post}
    />
))} */}

                        <CardProject />
                        <CardProject />
                        <CardProject />

                        <CardProject />
                        <CardProject />

                    </div>
                </div>

            </Container>
        </>
    );
}

export default Proyectos;
